name: dict_reader
description: Reading mdict files, support MDX/MDD file formats. It can simplify your writing of mdict-based dictionary software.
version: 1.1.4
repository: https://github.com/mumu-lhl/dict_reader

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

dependencies:
  charset: ^2.0.1
  blockchain_utils: ">=3.4.0 <5.0.0"
