name: dict_reader
description: Reading mdict files, support MDX/MDD file formats.
version: 1.0.2
repository: https://github.com/mumu-lhl/dict_reader

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

dependencies:
  charset: ^2.0.1
